project:
  type: website
  output-dir: "."

website:
  title: "Dylan Rogers"
  navbar:
    search: false
    background: "#1c4982"
    pinned: true
    left:
      - text: Home
        href: index.qmd
        
      - text: About
        href: about.qmd
        
      #- text: Projects
      #  href: projects.qmd

  page-footer: 
      center: "Powered with GitHub, and RStudio<br>© Dylan Rogers, 2025"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    preferred-color-scheme: auto
    mainfont: system-ui
    highlight-style: atom-one  # atom-one espresso
    toc: false